name: NewSystem
main: me.newdavis.spigot.plugin.NewSystem
version: 1.3
author: NewDavis
website: https://newdavis.me/
soft depend:
  - NewPerm

commands:
  newsystem:
    aliases: [ns]
  gamemode:
  gms:
    aliases: [gm0]
  gmc:
    aliases: [gm1]
  gma:
    aliases: [gm2]
  gmsp:
    aliases: [gm3]
  fly:
  speed:
  heal:
  feed:
  back:
  enderchest:
  invsee:
  craftingtable:
  anvil:
  enchantingtable:
  kit:
  give:
  giveall:
  spawnmob:
  raffle:
  clear:
  dupe:
  itemedit:
  repair:
  skull:
  hat:
  backpack:
  garbage:
  ja:
  nein:
  poll:
  peace:
  god:
  freeze:
  vanish:
  privatemessage:
  build:
  hologram:
  currency:
  pay:
  playtime:
  clearlag:
  teleporthere:
  teleport:
  teleportall:
  teleportaskall:
  teleportaccept:
  teleportask:
  teleportaskhere:
  home:
  spawn:
  warp:
  list:
  authentication:
  ban:
  banip:
  unban:
  mute:
  muteip:
  unmute:
  kick:
  warn:
  showip:
  history:
  maintenance:
  sudo:
  commandspy:
  globalmute:
  clearchat:
  broadcast:
  teamchat:
  buildchat:
  adminchat:
  support:
  supportmessage:
  report:
  stats:
  role:
  voucher:
  generator:
  day:
  night:
  ping: